server:
  port: 8080


spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/swp490_spa
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-23-23-128-222.compute-1.amazonaws.com:5432/d94nh5l6qrrsgk
    username: eiqbwqqlteaaqc
    password: e46ae95a83614c0d6effea4654dc408cac7f6719708460737cece689da7447f4
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
